# Generated by Django 5.0.6 on 2024-06-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Managerid', models.AutoField(primary_key=True, serialize=False)),
                ('Managername', models.CharField(max_length=20)),
                ('Manageremail', models.EmailField(max_length=100)),
                ('Managerphone_number', models.CharField(max_length=15)),
                ('ManagerPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RESIDENT',
            fields=[
                ('Resid', models.AutoField(primary_key=True, serialize=False)),
                ('Resname', models.CharField(max_length=20)),
                ('Resemail', models.CharField(max_length=100)),
                ('Resphonenumber', models.CharField(max_length=15)),
                ('ResPassword', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.manager')),
            ],
        ),
        migrations.CreateModel(
            name='REPORT',
            fields=[
                ('ResNumberHouse', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ResCategory', models.CharField(max_length=15)),
                ('ResDescription', models.CharField(max_length=1000)),
                ('Resname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.resident')),
            ],
        ),
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('ResNumberHouse', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ResidentPurpose', models.CharField(max_length=100)),
                ('ResidentStart', models.CharField(max_length=15)),
                ('ResidentEnd', models.CharField(max_length=15)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.manager')),
                ('Resname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.resident')),
            ],
        ),
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('Staffid', models.AutoField(primary_key=True, serialize=False)),
                ('Staffname', models.CharField(max_length=20)),
                ('Staffemail', models.CharField(max_length=100)),
                ('Staffphonenumber', models.CharField(max_length=15)),
                ('StaffPassword', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('Duties_number', models.AutoField(primary_key=True, serialize=False)),
                ('Assignto', models.CharField(max_length=1000)),
                ('Duedate', models.CharField(max_length=1000)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.manager')),
                ('Staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('VisitorName', models.AutoField(primary_key=True, serialize=False)),
                ('VisitorNumberIC', models.CharField(max_length=15)),
                ('VisitorHouseNumber', models.CharField(max_length=20)),
                ('VisitorPurpose', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor_subproject.manager')),
            ],
        ),
    ]
